In [1]:
import pickle
import numpy as np

In [3]:
ohe_sex=pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked=pickle.load(open('models/ohe_embarked.pkl','rb'))
clf=pickle.load(open('models/clf.pkl','rb'))

In [4]:
##give test new values for prediction

In [5]:
##ASUME USER INPUT
#Pclass/gender/age/SibSp/Parch/Fare/Embarked
## here we have to repeat same step of imputing, endoing, 

In [6]:
test_input=np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [7]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [8]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [9]:
test_input_embarked

array([[0., 0., 1.]])

In [12]:
test_input_age=test_input[:,2].reshape(1,1)

In [13]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age, test_input_sex, test_input_embarked), axis=1)


In [14]:
test_input_transformed

array([[2, 0, 0, 10.5, 31.0, 0.0, 1.0, 0.0, 0.0, 1.0]], dtype=object)

In [15]:
clf.predict(test_input_transformed)

array([1], dtype=int64)

In [16]:
## output is 1